name: Reformats source files
# write [skip reformat] to skip this workflow!

on:
  push:
    branches: [ master ]

env:
  ACTIONS_PYTHON_VERSION: 3.9


jobs:
  reformat:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip reformat]')"
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.ACTIONS_PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.ACTIONS_PYTHON_VERSION }}
    - name: Install Python Dependencies
      run: pip install black
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install npm dependencies
      run: npm ci
    - name: Reformat data files
      run: ./libexec/altlabel_utils.py format
    - name: Reformat Python files
      run: black .
    - name: Reformat JavaScript
      run: npx eslint --fix src/ cypress/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "style: reformat files"
        branch-suffix: short-commit-hash
        commit-message: |
          style: reformat files

          [skip deploy]
        delete-branch: true
